# Generated by Django 4.0.2 on 2022-02-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='name',
            new_name='bucket_name',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_name',
        ),
    ]
