# Generated by Django 4.0.2 on 2022-02-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_name_bucket_bucket_name_remove_poll_poll_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='wallet_code',
            new_name='wallet_address',
        ),
    ]
